name: har
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pytorch
  - numpy
  - scipy
  - pandas
  - pyyaml
  - lightning
  - pytorch-lightning
  - torchmetrics
  - matplotlib
  - seaborn
  - hydra-core
  - wandb
  - optuna
  - hydra-optuna-sweeper
  - pip
  - pip:
      - hydra-submitit-launcher
      - submitit