# Scenario 3: Secondary pose-only dataset (UTD + NTU)
# Extends scenario2_utd with secondary pose stream from NTU
defaults:
  - _self_

trial_name: scenario3_utd

data:
  name: utd

  sensor_window_length: 100
  stride_seconds: 0.1
  batch_size: 32

optim:
  name: adam

  lr: 0.001
  weight_decay: 0.00002

  warmup_epochs: 10
  warmup_start_factor: 0.02

  scheduler:
    patience: 15
    factor: 0.05

trainer:
  name: scenario2

  alpha: 0.2
  beta: 2
  gamma: 1

  epochs: 100
  patience: 35
  gradient_clip: 1.0

  # Scenario 3 specific: enable secondary dataset
  secondary:
    enabled: true
    data: ntu50.yaml  # 50Hz to match UTD sampling rate
    n_classes: 60
    loss_weight: 1.0

model:
  regressor:
    name: regressor
  encoder_classifier:
    name: mmfit
    n_classes: 21
