# Scenario 24: Separate feature extractors (MMFit)
# Extends scenario2_mmfit with separate_feature_extractors=true
# Real IMU → fe, Simulated IMU → fe_sim (classifier shared)
defaults:
  - _self_

trial_name: scenario24_mmfit

# Artifact control
save_artifacts: true      # Save history to JSON + generate plots
save_checkpoints: true    # Save model weights

data:
  name: mmfit

  sensor_window_length: 300
  stride_seconds: 0.2
  batch_size: 64

optim:
  name: adam

  lr: 0.0006748457174302904
  weight_decay: 1.8176473540274426e-05

  warmup_epochs: 0
  warmup_start_factor: 0.05

  scheduler:
    patience: 8
    factor: 0.05

trainer:
  name: scenario2

  alpha: 0.5
  beta: 2
  gamma: 2.0

  epochs: 200
  patience: 25
  gradient_clip: 1.0
  label_smoothing: 0.1

  # Scenario 24 specific: separate feature extractors for real vs sim
  separate_feature_extractors: true

model:
  regressor:
    name: regressor
    joint_dropouts: [0.2, 0.3, 0.3, 0.3]
    temporal_dropout: 0.1
  encoder_classifier:
    name: mmfit
    n_classes: 11
    feature_extractor:
      drop_prob: 0.2
    classifier:
      dropout: 0.2
