defaults:
  - _self_

trial_name: scenario2_mmfit

# Artifact control
save_artifacts: true      # Save history to JSON + generate plots
save_checkpoints: true    # Save model weights

data:
  name: mmfit

  sensor_window_length: 400
  stride_seconds: 0.2
  batch_size: 64

optim:
  name: adam

  lr: 0.0003120891284394599
  weight_decay: 1.1534317012820964e-05

  warmup_epochs: 5
  warmup_start_factor: 0.05

  scheduler:
    patience: 15
    factor: 0.2

trainer:
  name: scenario2

  alpha: 0.5
  beta: 1
  gamma: 2

  epochs: 200
  patience: 25
  gradient_clip: 1.0

  label_smoothing: 0.05


model:
  regressor:
    name: regressor

    joint_dropouts: [0.0, 0.2, 0.2, 0.2]
    temporal_dropout: 0.3

    joint_hidden_channels: [32, 32, 32, 32]
    temporal_hidden_channels: 12
    joint_kernel_sizes: [3, 3, 3, 3]

  encoder_classifier:
    name: mmfit
    n_classes: 11

    feature_extractor:
      name: mmfit_encoder
      drop_prob: 0.3

      kernel_size: 7
      base_filters: [8, 12, 16]
      embedding_dim: 80

    classifier:
      name: mlp_classifier
      dropout: 0.2
      hidden_units: [128]

