# Scenario 4: Adversarial domain adaptation (UTD)
# Extends scenario2_utd with feature-level discriminator + GRL
defaults:
  - _self_

trial_name: scenario4_utd

# Artifact control
save_artifacts: true      # Save history to JSON + generate plots
save_checkpoints: false    # Save model weights

data:
  name: utd

  sensor_window_length: 100
  stride_seconds: 0.02
  batch_size: 8

optim:
  name: adam

  lr: 0.001
  weight_decay: 0.00002

  warmup_epochs: 10
  warmup_start_factor: 0.02

  scheduler:
    patience: 15
    factor: 0.05

trainer:
  name: scenario2

  alpha: 0.2
  beta: 2
  gamma: 1

  epochs: 100
  patience: 35
  gradient_clip: 1.0

  # Scenario 4 specific: enable adversarial training with feature-level GRL
  adversarial:
    enabled: true
    weight: 0.1
    use_grl: true
    grl_lambda: 1.0
    schedule_lambda: true  # Enable DANN-style scheduling
    pretrain_epochs: 0     # Epochs to train with MSE only before adversarial (0 = disabled)
    discriminator:
      input_type: features
      hidden_units: [128, 64]
      dropout: 0.3
      normalize_features: false   # L2 normalize for stable training
      use_spectral_norm: false    # Optional: constrain D capacity
      label_smoothing: 0.05       # Prevent overconfident D
      # ACGAN: class-conditional with auxiliary classifier (disabled by default)
      use_acgan: false
      aux_weight: 1.0
      embed_dim: 32

model:
  regressor:
    name: regressor
  encoder_classifier:
    name: mmfit
    n_classes: 21
