# Scenario 4: Adversarial domain adaptation (MMFit)
# Extends scenario2_mmfit with feature-level discriminator + GRL
defaults:
  - _self_

trial_name: scenario4_mmfit

# Artifact control
save_artifacts: false      # Save history to JSON + generate plots
save_checkpoints: false    # Save model weights

data:
  name: mmfit

  sensor_window_length: 500
  stride_seconds: 0.2
  batch_size: 64

optim:
  name: adam

  lr: 0.0005
  weight_decay: 0.00002

  warmup_epochs: 5
  warmup_start_factor: 0.05

  scheduler:
    patience: 10
    factor: 0.05

trainer:
  name: scenario2

  alpha: 0.2
  beta: 5
  gamma: 1

  epochs: 200
  patience: 25
  gradient_clip: 1.0

  # Scenario 4 specific: enable adversarial training
  adversarial:
    enabled: true
    weight: 0.1
    use_grl: true
    grl_lambda: 1.0
    schedule_lambda: true  # Enable DANN-style scheduling
    discriminator:
      hidden_units: [64]
      dropout: 0.3
      normalize_features: true   # L2 normalize for stable training
      use_spectral_norm: false   # Optional: constrain D capacity
      label_smoothing: 0.1       # Prevent overconfident D

model:
  regressor:
    name: regressor
  encoder_classifier:
    name: mmfit
    n_classes: 11
