# Scenario 24: Separate feature extractors (UTD)
# Extends scenario2_utd with separate_feature_extractors=true
# Real IMU → fe, Simulated IMU → fe_sim (classifier shared)
defaults:
  - _self_

trial_name: scenario24_utd

# Artifact control
save_artifacts: true      # Save history to JSON + generate plots
save_checkpoints: true    # Save model weights

data:
  name: utd

  sensor_window_length: 100
  stride_seconds: 0.1
  batch_size: 16

optim:
  name: adam

  lr: 0.001013756549502438
  weight_decay: 2.0424668961468034e-05

  warmup_epochs: 5
  warmup_start_factor: 0.02

  scheduler:
    patience: 10
    factor: 0.05

trainer:
  name: scenario2

  alpha: 5
  beta: 100
  gamma: 1

  epochs: 100
  patience: 25
  gradient_clip: 1.0
  label_smoothing: 0.05

  # Scenario 24 specific: separate feature extractors for real vs sim
  separate_feature_extractors: true

model:
  regressor:
    name: regressor
    joint_hidden_channels: [32, 32, 32, 32]
    temporal_hidden_channels: 16
  encoder_classifier:
    name: mmfit
    n_classes: 21
    feature_extractor:
      kernel_size: 5
      base_filters: [6, 9, 12]
      embedding_dim: 64
      drop_prob: 0.1
    classifier:
      hidden_units: [64, 64]
      dropout: 0.2
