defaults:
  - _self_

seed: 0

trial_name: scenario2_utd

alpha: 0.2
beta: 2
gamma: 1

data:
  name: utd
  sensor_window_length: 100 # Best
  stride_seconds: 0.1 # Best
  batch_size: 32

optim:
  name: adam
  lr: 0.001
  weight_decay: 0.00002
  warmup_epochs: 10
  warmup_start_factor: 0.02
  scheduler:
    patience: 15
    factor: 0.05

trainer:
  name: scenario2
  epochs: 100
  patience: 25
  gradient_clip: 1.0 # Best
  # objective:
  #   metric: val_f1
  #   mode: max
  # trainable_modules:
  #   pose2imu: true
  #   fe: true
  #   ac: true
  # losses:
  #   mse: true
  #   feature_similarity: true
  #   activity: true
  #   activity_real: true
  #   activity_sim: true

model:
  feature_extractor:
    name: feature_extractor
    # n_filters: 16
    # filter_size: 7
  regressor:
    name: regressor
    use_batch_norm: true
    # joint_hidden_channels: [64, 64, 32, 32]
    # joint_kernel_sizes: [3, 3, 3, 1]
    # joint_dilations: [1, 2, 4, 1]
    # joint_dropouts: [0.0, 0.1, 0.1, 0.1]
    # temporal_hidden_channels: 16
    # temporal_kernel_size: 5
    # temporal_dilation: 1
    # temporal_dropout: 0.4
    # fc_hidden: 0
    # fc_dropout: 0.25
  classifier:
    name: classifier
    f_in: 100
    n_classes: 21
