# Scenario 3: Secondary pose-only dataset (MMFit + NTU)
# Extends scenario2_mmfit with secondary pose stream from NTU
defaults:
  - _self_

trial_name: scenario3_mmfit

# Artifact control
save_artifacts: true      # Save history to JSON + generate plots
save_checkpoints: true    # Save model weights

data:
  name: mmfit

  sensor_window_length: 250
  stride_seconds: 0.2
  batch_size: 64

optim:
  name: adam

  lr: 0.00039830659264117427
  weight_decay: 1.4756599212344335e-05

  warmup_epochs: 0
  warmup_start_factor: 0.05

  scheduler:
    patience: 10
    factor: 0.2

trainer:
  name: scenario2

  alpha: 2
  beta: 2
  gamma: 2

  epochs: 200
  patience: 25
  gradient_clip: 1.0
  label_smoothing: 0.05

  # Scenario 3 specific: enable secondary dataset
  secondary:
    enabled: true
    data: ntu100.yaml  # 100Hz to match MMFit sampling rate
    n_classes: 60
    loss_weight: 0.25

model:
  regressor:
    name: regressor
    joint_dropouts: [0.0, 0.2, 0.2, 0.2]
    temporal_dropout: 0.3
  encoder_classifier:
    name: mmfit
    n_classes: 11
    feature_extractor:
      drop_prob: 0.2
    classifier:
      dropout: 0.2
