# Scenario 25: No feature similarity loss (UTD)
# Extends scenario2_utd with beta=0 (drop cosine similarity term)
# Purpose: Test what beta contributes to training
defaults:
  - _self_

trial_name: scenario25_utd

# Artifact control
save_artifacts: true      # Save history to JSON + generate plots
save_checkpoints: true    # Save model weights

data:
  name: utd

  sensor_window_length: 100
  stride_seconds: 0.1
  batch_size: 16

optim:
  name: adam

  lr: 0.0018473588760600488
  weight_decay: 3.2540242263016536e-05

  warmup_epochs: 10
  warmup_start_factor: 0.02

  scheduler:
    patience: 15
    factor: 0.2

trainer:
  name: scenario2

  alpha: 2
  beta: 0   # Scenario 25: no feature similarity loss
  gamma: 0.5

  epochs: 100
  patience: 25
  gradient_clip: 1.0
  label_smoothing: 0.1

  # Scenario 25 specific: disable feature similarity loss
  losses:
    feature_similarity: false

model:
  regressor:
    name: regressor
    joint_hidden_channels: [24, 24, 24, 24]
    temporal_hidden_channels: 16
    joint_kernel_sizes: [5, 5, 5, 5]
    joint_dropouts: [0.2, 0.3, 0.3, 0.3]
    temporal_dropout: 0.2
  encoder_classifier:
    name: mmfit
    n_classes: 21
    feature_extractor:
      kernel_size: 9
      base_filters: [6, 9, 12]
      embedding_dim: 80
      drop_prob: 0.1
    classifier:
      hidden_units: [128]
      dropout: 0.5
