# Scenario 25: No feature similarity loss (MM-Fit)
# Extends scenario2_mmfit with beta=0 (drop cosine similarity term)
# Purpose: Test what beta contributes to training
defaults:
  - _self_

trial_name: scenario25_mmfit

# Artifact control
save_artifacts: true      # Save history to JSON + generate plots
save_checkpoints: true    # Save model weights

data:
  name: mmfit

  sensor_window_length: 500
  stride_seconds: 0.2
  batch_size: 64

optim:
  name: adam

  lr: 0.0003060236651813944
  weight_decay: 1.0096269449087514e-05

  warmup_epochs: 5
  warmup_start_factor: 0.05

  scheduler:
    patience: 10
    factor: 0.05

trainer:
  name: scenario2

  alpha: 5
  beta: 0   # Scenario 25: no feature similarity loss
  gamma: 50

  epochs: 200
  patience: 25
  gradient_clip: 1.0
  label_smoothing: 0.1

  # Scenario 25 specific: disable feature similarity loss
  losses:
    feature_similarity: false

model:
  regressor:
    name: regressor
    joint_hidden_channels: [32, 32, 32, 32]
    temporal_hidden_channels: 8
    joint_kernel_sizes: [3, 3, 3, 3]
    joint_dropouts: [0.0, 0.2, 0.2, 0.2]
    temporal_dropout: 0.3
  encoder_classifier:
    name: mmfit
    n_classes: 11
    feature_extractor:
      kernel_size: 9
      base_filters: [8, 12, 16]
      embedding_dim: 80
      drop_prob: 0.3
    classifier:
      hidden_units: [128]
      dropout: 0.3
