defaults:
  - _self_

## Scenario 2 trial configuration
trial_name: scenario2_mmfit

# Data overrides (merged on top of conf/data/mmfit.yaml)
data:
  name: mmfit
  overrides:
    sensor_window_length: 400
    stride_seconds: 0.1

# Loss weighting coefficients consumed by the manual Trainer
alpha: 100   # weight for activity classification component
beta: 1    # weight for feature similarity component
gamma: 1    # weight for regression (MSE) component

model:
  feature_extractor:
    n_filters: 16
    filter_size: 3
  regressor:
    joint_hidden_channels: [32, 32, 32, 16]
    joint_kernel_sizes: [5, 5, 5, 1]
    joint_dilations: [1, 3, 5, 1]
    joint_dropouts: [0.1, 0.3, 0.3, 0.3]
    temporal_hidden_channels: 48
    temporal_kernel_size: 5
    temporal_dilation: 1
    temporal_dropout: 0.1
    fc_hidden: 128
    fc_dropout: 0.1
    use_batch_norm: true
  classifier:
    f_in: 100
    n_classes: 11

optim:
  name: adam
  lr: 0.00044303752452182633
  weight_decay: 0.0007257005721594283
  warmup_epochs: 8
  warmup_start_factor: 0.24691424506821164
  scheduler:
    name: reduce_on_plateau
    mode: min
    factor: 0.1
    patience: 10

trainer:
  name: scenario2
  epochs: 100
  patience: 10
