# Scenario 22: No MSE/regression (MMFit)
# Extends scenario2_mmfit with gamma=0 (drop regression term)
defaults:
  - _self_

trial_name: scenario22_mmfit

# Artifact control
save_artifacts: false      # Save history to JSON + generate plots
save_checkpoints: false    # Save model weights

data:
  name: mmfit

  sensor_window_length: 500
  stride_seconds: 0.2
  batch_size: 64

optim:
  name: adam

  lr: 0.0005
  weight_decay: 0.00002

  warmup_epochs: 5
  warmup_start_factor: 0.05

  scheduler:
    patience: 10
    factor: 0.05

trainer:
  name: scenario2

  alpha: 0.2
  beta: 5
  gamma: 0  # Scenario 22: no regression loss

  epochs: 200
  patience: 25
  gradient_clip: 1.0

  # Scenario 22 specific: disable MSE loss
  losses:
    mse: false

model:
  regressor:
    name: regressor
  encoder_classifier:
    name: mmfit
    n_classes: 11
