# Scenario 4: Adversarial domain adaptation (UTD)
# Extends scenario2_utd with feature-level discriminator + GRL
defaults:
  - _self_

trial_name: scenario4_utd

data:
  name: utd

  sensor_window_length: 100
  stride_seconds: 0.1
  batch_size: 32

optim:
  name: adam

  lr: 0.001
  weight_decay: 0.00002

  warmup_epochs: 10
  warmup_start_factor: 0.02

  scheduler:
    patience: 15
    factor: 0.05

trainer:
  name: scenario2

  alpha: 0.2
  beta: 2
  gamma: 1

  epochs: 100
  patience: 35
  gradient_clip: 1.0

  # Scenario 4 specific: enable adversarial training
  adversarial:
    enabled: true
    weight: 0.1
    use_grl: true
    grl_lambda: 1.0
    schedule_lambda: false
    discriminator:
      hidden_units: [64]
      dropout: 0.3

model:
  regressor:
    name: regressor
  encoder_classifier:
    name: mmfit
    n_classes: 21
