defaults:
  - _self_

seed: 0

## Scenario 2 trial configuration
trial_name: scenario2_mmfit

# Loss weighting coefficients
alpha: 1 # weight for activity classification
beta: 1 # weight for feature similarity
gamma: 1 # weight for regression (MSE)

# Data configuration (merged on top of conf/data/mmfit.yaml)
data:
  name: mmfit
  sensor_window_length: 500
  stride_seconds: 0.2
  batch_size: 128

## Params
optim:
  name: adam
  lr: 0.001
  # weight_decay: 0.0001
  warmup_epochs: 15
  warmup_start_factor: 0.05
  scheduler:
    patience: 12

trainer:
  name: scenario2
  epochs: 200
  patience: 25
  # gradient_clip: null
  # trainable_modules:
  #   pose2imu: true
  #   fe: true
  #   ac: true
  # losses:
  #   mse: true
  #   feature_similarity: true
  #   activity: true
  #   activity_real: true
  #   activity_sim: true

model:
  feature_extractor:
    name: feature_extractor
  #   n_filters: 16
  #   filter_size: 7
  regressor:
    name: regressor
  #   joint_hidden_channels: [64, 64, 32, 32]
  #   joint_kernel_sizes: [3, 3, 3, 1]
  #   joint_dilations: [1, 2, 4, 1]
  #   joint_dropouts: [0.0, 0.1, 0.1, 0.1]
  #   temporal_hidden_channels: 16
  #   temporal_kernel_size: 7
  #   temporal_dilation: 2
  #   temporal_dropout: 0.4
  #   fc_hidden: 0
  #   fc_dropout: 0.25
  #   use_batch_norm: false
classifier:
  f_in: 100
  n_classes: 11
