# Scenario 42: Signal-level adversarial domain adaptation (UTD)
# Like scenario 4, but discriminator operates on raw accelerometer data
# instead of encoder features.
#
# Key difference from Scenario 4:
# - Scenario 4:  D(features) - discriminator on encoder output
# - Scenario 42: D(accelerometer) - discriminator on raw signal
#
# This directly trains the regressor (pose2imu) to produce realistic
# accelerometer signals, rather than relying on the encoder to align features.
defaults:
  - _self_

trial_name: scenario42_utd

# Artifact control
save_artifacts: true       # Save history to JSON + generate plots
save_checkpoints: false    # Save model weights

data:
  name: utd

  sensor_window_length: 100
  n_channels: 3            # Accelerometer channels (x, y, z)
  stride_seconds: 0.02
  batch_size: 8

optim:
  name: adam

  lr: 0.001
  weight_decay: 0.00002

  warmup_epochs: 10
  warmup_start_factor: 0.02

  scheduler:
    patience: 15
    factor: 0.05

trainer:
  name: scenario2

  alpha: 1.0           # Activity classification weight
  beta: 0              # No cosine sim - adversarial on signal replaces it
  gamma: 1.0           # MSE loss weight

  epochs: 100
  patience: 35
  gradient_clip: 1.0

  # Scenario 42 specific: adversarial on raw accelerometer with WGAN-GP
  # Uses alternating D/G updates (proper WGAN training, not GRL)
  adversarial:
    enabled: true
    weight: 0.5              # Adversarial weight for G loss
    use_grl: false           # WGAN uses alternating updates, not GRL
    alternating: true        # Enable alternating D/G optimization
    n_critic: 5              # D updates per G update (standard for WGAN-GP)
    pretrain_epochs: 15      # Train regressor with MSE for 15 epochs first
    discriminator:
      input_type: signal     # KEY: D operates on raw acc, not features
      hidden_channels: [32, 64]  # 1D CNN channels for signal processing
      dropout: 0.3
      use_spectral_norm: false
      label_smoothing: 0.0   # Not used for WGAN
      loss_type: wgan        # WGAN-GP for better signal-level gradients
      lambda_gp: 10.0        # Gradient penalty coefficient
      # ACGAN: class-conditional discrimination (optional, searchable via HPO)
      use_acgan: false       # Enable to add class conditioning + aux classifier
      aux_weight: 1.0        # Weight for aux classification loss
      embed_dim: 32          # Class label embedding dimension
      n_classes: 21          # Must match model.encoder_classifier.n_classes

model:
  regressor:
    name: regressor
  encoder_classifier:
    name: mmfit
    n_classes: 21
