# Optimizer config group
name: adam
lr: 0.001
weight_decay: 0.0001
warmup_epochs: 12
warmup_start_factor: 0.05
scheduler:
  name: reduce_on_plateau
  mode: min
  factor: 0.1
  patience: 12  # epochs to wait without val-loss improvement before lowering lr
