defaults:
  - _self_

## Scenario 2 experiment configuration
experiment_name: scenario2

# Loss weighting coefficients consumed by the manual Trainer
alpha: 100   # weight for activity classification component
beta: 1    # weight for feature similarity component
gamma: 1    # weight for regression (MSE) component

model:
  regressor:
    joint_hidden_channels: [48, 48, 32, 16]
    joint_kernel_sizes: [7, 5, 3, 1]
    joint_dilations: [1, 3, 5, 1]
    joint_dropouts: [0.0, 0.2, 0.2, 0.2]
    temporal_hidden_channels: 24
    temporal_kernel_size: 5
    temporal_dilation: 2
    temporal_dropout: 0.1
    fc_hidden: 64
    fc_dropout: 0.1
    use_batch_norm: true
  feature_extractor:
    n_filters: 20
    filter_size: 7
  classifier:
    f_in: 100
    n_classes: 11

optim:
  name: adam
  lr: 0.0012809165658884784
  weight_decay: 5.604139607438746e-05
  scheduler:
    name: reduce_on_plateau
    mode: min
    factor: 0.1
    patience: 10

trainer:
  epochs: 100
  patience: 10