dataset_name: mmfit

# Cluster data directory - same structure as local, different base path
data_dir: '/netscratch/zolfaghari/data/mm-fit/'

# Cluster-specific optimizations
cluster: true
num_workers: 8
batch_size: 128  # Larger batch size for cluster

models:
    regressor:
        params:
            sequence_length: 300
            hidden_channels: 64  # Larger model for cluster

    feature_extractor:
        n_filters: 16  # More filters
        n_dense: 128   # Larger dense layer
        
    classifier:
        f_in: 128  # Match feature_extractor.n_dense

loss_coefficients:
    alpha: 1.0
    beta: 0.1

# Training settings optimized for cluster
epochs: 200
lr: 1e-3
patience: 20

# Use more data on cluster (disable subset selection)
use_full_dataset: true
