dataset_name: mmfit

# Scenario 2 configuration for local development
# Uses data_dir from base.yaml (./data/mm-fit/)

models:
    regressor:
        params:
            sequence_length: 300

loss_coefficients:
    alpha: 1.0
    beta: 0.1